services:
  - type: web
    region: ohio
    name: backend-service
    env: python
    buildCommand: "./render_build.sh"
    startCommand: "cd src && gunicorn app:app"
    plan: free
    envVars:
      - key: BASENAME
        value: /
      - key: FLASK_APP
        value: src/app.py
      - key: FLASK_DEBUG
        value: 0
      - key: DATABASE_URL
        fromDatabase:
          name: postgresql-trapezoidal-42170
          property: connectionString

  - type: web
    region: ohio
    name: frontend-service
    env: static
    buildCommand: npm run build
    staticPublishPath: ./build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

databases:
  - name: postgresql-trapezoidal-42170
    region: ohio
    ipAllowList: []
    plan: free