"""empty message

Revision ID: 00e2bc061f8a
Revises: 
Create Date: 2024-10-16 12:23:45.311351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00e2bc061f8a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_de_categoria', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nombres', sa.String(length=30), nullable=True),
    sa.Column('apellidos', sa.String(length=20), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('creado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('restaurantes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=False),
    sa.Column('cubiertos', sa.Integer(), nullable=True),
    sa.Column('cantidad_mesas', sa.Integer(), nullable=True),
    sa.Column('horario_mañana_inicio', sa.Time(), nullable=True),
    sa.Column('horario_mañana_fin', sa.Time(), nullable=True),
    sa.Column('horario_tarde_inicio', sa.Time(), nullable=True),
    sa.Column('horario_tarde_fin', sa.Time(), nullable=True),
    sa.Column('reservas_por_dia', sa.Integer(), nullable=True),
    sa.Column('registro_completo', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('categorias_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categorias_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('mesas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.Column('ubicacion', sa.String(length=30), nullable=True),
    sa.Column('capacidad', sa.Integer(), nullable=True),
    sa.Column('disponibilidad', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reserva',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('fecha_reserva', sa.DateTime(), nullable=False),
    sa.Column('trona', sa.Integer(), nullable=True),
    sa.Column('adultos', sa.Integer(), nullable=False),
    sa.Column('niños', sa.Integer(), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.Column('creada', sa.DateTime(), nullable=True),
    sa.Column('modificada', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurantes_favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('restaurantes_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['restaurantes_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valoracion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('restaurante_id', sa.Integer(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valoracion')
    op.drop_table('restaurantes_favoritos')
    op.drop_table('reserva')
    op.drop_table('mesas')
    op.drop_table('restaurantes')
    op.drop_table('usuario')
    op.drop_table('categorias')
    # ### end Alembic commands ###
