"""empty message

Revision ID: 6650cfffb7fe
Revises: b8bbdcfa4f71
Create Date: 2024-10-17 00:46:18.207337

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6650cfffb7fe'
down_revision = 'b8bbdcfa4f71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descripcion', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_column('descripcion')

    # ### end Alembic commands ###
