"""empty message

Revision ID: db974d810998
Revises: 26f9e87fc949
Create Date: 2025-03-15 02:13:35.247145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db974d810998'
down_revision = '26f9e87fc949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('horario_mañana_inicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('horario_mañana_fin', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('horario_tarde_inicio', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('horario_tarde_fin', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_column('horario_tarde_fin')
        batch_op.drop_column('horario_tarde_inicio')
        batch_op.drop_column('horario_mañana_fin')
        batch_op.drop_column('horario_mañana_inicio')

    # ### end Alembic commands ###
